#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    
    for f in /etc/X11/xinit/xinitrc.d/*; do
    
        [ -x "$f" ] && . "$f"
    done
    
    unset f
fi

[ -f ~/.Xresources ] && xrdb -merge -I"${HOME}" ~/.Xresources

#xset s off
xset b off
#xset -dpms
#xset s noblank
xset s 300
xset dpms 0 0 600
xset r rate 200 20

# Keyboard
setxkbmap en
setxkbmap -option ctrl:nocaps
xmodmap -e 'clear lock'
xmodmap -e 'keycode 66 = Hyper_L'

# Monitor
xrandr --output HDMI-1 --mode 2560x1440 --primary --current

xrandr --output eDP-1 --off
#xrandr --output eDP-1 --mode 1920x1080 --left-of HDMI-1

# nvidia-settings --load-config-only

exec /bin/i3 && exit #-V >> ~/.i3/i3log 2>&1
#exec cinnamon-session
