user_pref("browser.download.dir", "/home/nafaryus/downloads");
user_pref("browser.download.autohideButton", false);
user_pref("browser.library.activity-stream.enabled", false);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.urlbar.decodeURLsOnCopy", true);
user_pref("browser.startup.homepage", "about:blank");
user_pref("extensions.pocket.enabled", false);
user_pref("media.hardwaremediakeys.enabled", true);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("font.name.serid.x-western", "Fira Code");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"urlbar-container\",\"stop-reload-button\",\"downloads-button\",\"history-panelmenu\",\"library-button\",\"print-button\",\"fxa-toolbar-menu-button\",\"jid1-niffy2ca8fy1tg_jetpack-browser-action\",\"rto_rto_rto-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"managed-bookmarks\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"jid1-niffy2ca8fy1tg_jetpack-browser-action\",\"rto_rto_rto-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":4}");
