#!/usr/bin/env bash
# usage: extractor <archieve>
extractor() {
    if [ -f $1 ] ; then
        case $1 in
            *.tar.bz2|*.tbz2)   
                tar xjf $1 
                ;;  
            *.tar.gz|*.tgz)    
                tar xzf $1   
                ;;  
            *.bz2)       
                bunzip2 $1   
                ;;  
            *.rar)       
                unrar x $1     
                ;;  
            *.gz)        
                gunzip $1    
                ;;  
            *.tar)       
                tar xf $1    
                ;;  
            *.zip)       
                unzip $1     
                ;;  
            *.Z)         
                uncompress $1
                ;;
            *.7z)        
                7z x $1      
                ;;  
            *.xz)        
                unxz $1    
                ;;
            *)           
                echo "error: '$1' cannot be extracted via extractor()" 
                ;;
        esac
    else
        echo "error: '$1' is not a valid file"
    fi  
}
